spring:
  datasource:
    url: jdbc:postgresql://database:5432/dental_clinic_repository
    username: postgres
    password: postgres
  jpa.open-in-view: false

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: mailDetails:org.ilia.appointmentservice.entity.MailDetails

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}

keycloak:
  server-url: http://keycloak:8001
  realm: dental-clinic-realm
  client-id: dental-clinic-client
  client-secret: St10t32DmZStwE04v4paHNUhC2AF8Ydf

eureka:
  instance.prefer-ip-address: true
  client.serviceUrl.defaultZone: http://eureka:8002/eureka/

server.port: 8012

management.endpoints.web.exposure.include: "*"