spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dental_clinic_repository
    username: postgres
    password: postgres
  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}

keycloak:
  server-url: http://keycloak:8001
  realm: dental-clinic-realm
  client-id: dental-clinic-client
  client-secret: St10t32DmZStwE04v4paHNUhC2AF8Ydf

server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: "*"